### ISSUE TITLE
Snapping is unreliable

### ISSUE THREAD

**Issue by Athelena** [liberostelios/roads_generator#35] opened 2020-09-30 14:54 UTC
Many times, one of the two sides of a merge might not snap

**Comment by liberostelios** [comment] 2020-10-14 11:29
I am unable to reproduce the problem after a fresh run. Checked with the case mentioned in #25 (in Poznan dataset) and the snapping now worked.

I am assuming this is now fixed, after some adjustments in the geometry precision, but let's leave it open after we try on other datasets as well.

**Closed** 2020-12-08 14:01 UTC
Labels: bug
